### ISSUE TITLE
What is the AndroidSDK version of AppsFlyerAIRExtension-witout-gp.ane?

### ISSUE THREAD

**Issue by ulsan1635** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#13]
Hi~

I downloaded AppsFlyerAIRExtension-witout-gp.ane on August 17.

What is the AndroidSDK version of AppsFlyerAIRExtension-witout-gp.ane?

I read the link below and tried to test SDK integration.
https://support.appsflyer.com/hc/en-us/articles/210213753

When I clicked the [ SDK Integration Testing ] button,
testing is failed.

![image](https://cloud.githubusercontent.com/assets/8590017/17735869/ab892cba-64bf-11e6-8744-addfcb5512e5.png)

**Comment by af-dan** [comment]
Hi,
The Android SDK version for AppsFlyerAIRExtension is 4.5.0.
However, the SDK Integration Test App currently does not support this plugin, this is why this error is displayed.
