### ISSUE TITLE
getConversionData returns wrong results on Android

### ISSUE THREAD

**Issue by VoodooGames** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#2]
Hi,

We noticed a bug in the getConversionData() method : it doesn't work properly on Android.

During our test, AppsFlyer correctly attributed the app install to a "test" media source on the dashboard, but the media source returned by the ANE is not the same (we have "Organic").

We did the same test on iOS and it worked properly : the getConversionData() returned the proper media source.

```
appsFlyer.sendTracking();
appsFlyer.addEventListener(AppsFlyerEvent.INSTALL_CONVERSATION_DATA_LOADED, onConversionData);
appsFlyer.addEventListener(AppsFlyerEvent.INSTALL_CONVERSATION_FAILED, onConversionData);
appsFlyer.getConversionData();
```

Thanks for your help.

**Comment by gmeroz** [comment]
Did you call this  code after the sendTracking() is called?

**Comment by VoodooGames** [comment]
Yes. Should i call it before?

**Comment by VoodooGames** [comment]
I updated the code in the first post accordingly.

**Comment by sokoloff06** [comment]
Hi! 
We are closing this issue due to a lack of activity. Please feel free to re-open and let us know if that is still relevant. 
Thank you!
