### ISSUE TITLE
Android 64 bit compilation?

### ISSUE THREAD

**Issue by noamgat** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#21]
With the upcoming Android deprecation (apps released / updates submitted on august 1 2019 or later in google play store must support 64 bit), is it possible to provide a compilation of this ANE with support for android 64 bit?

**Comment by sokoloff06** [comment]
Hi @noamgat !

Currently, Adobe AIR doesn't support compilation for 64-bit platforms.

You can see relevant feature request to Adobe Team [here](https://tracker.adobe.com/#/view/AIR-4198789).

According to https://forums.adobe.com/thread/2598621 and https://forums.adobe.com/thread/2603957, 64-bit support should appear in next Adobe AIR 33 version.

As soon as the new AIR version is released we will recompile ANE.

Thank you!

**Comment by noamgat** [comment]
Hi Vitaly,

Harman (the new maintainers of Adobe Air) already have an Air 33 Beta
version, you can get access to it by mailing adobe.support@harman.com
They are very responsive, and are looking for feedback from the Adobe Air
plugin writers.

**Comment by sokoloff06** [comment]
@noamgat , thanks for sharing this information!

We have some concerns about using Beta version but would like to let you know that we are considering that option as well.

In the meantime just wanted to bring some attention that according to [Google blog post](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html), Google Play will continue to accept 32-bit only **updates to existing games** that use the following SDKs:
Corona Labs SDK - until August 2020
**Adobe Air software and the AIR SDK - until August 2020**
Unity 5.6.7 or older - until August 2021

Nevertheless, we are working on delivering a 64bit compatible version of AppsFlyer ANE as soon as possible.

**Comment by noamgat** [comment]
Thanks. I also saw the notice from a few days ago. It makes things less
urgent :)

**Comment by sokoloff06** [comment]
Hi everybody!

Happy to update you that we have recompiled ANEs for Android 64bit support using Harman Air SDK 33 and updated the repository with new binaries. Feel free to check it out
