### ISSUE TITLE
Wrong namespace in ANE for Adobe Air Sdk 33?

### ISSUE THREAD

**Issue by stiv-iv** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#22]
# Report

## Plugin Version

4.10.0

## On what Platform are you having the issue?

Adobe Air SDK 33. iOs

## What did you do?

Tried to package app with ane extension for appsflyer

## What did you expect to happen?

Build will be packaged

## What happened instead?

Build will not packaged

## Please provide any other relevant information.

I have message from packager: «Included native extension 'com.appsflyer.adobeair' specifies namespace 'http://ns.adobe.com/air/extension/33.0' which is greater than the application namespace: http://ns.adobe.com/air/application/32.0»

But latest AIR SDK from Harman (https://airsdk.harman.com/download) doesn't have namespace http://ns.adobe.com/air/extension/33.0. Instead they used old namespace http://ns.adobe.com/air/application/32.0 in Adobe Air SDK 33.

So I can't use ANE extension with latest AIR SDK.

**Comment by ironsolder9100** [comment]
i have same problem . any one have a solution ????

**Comment by James55p** [comment]
@stiv-iv @ironsolder9100 
I've contacted the support team & they've just released a fix for this (changed the namespace to 32)

**Comment by sokoloff06** [comment]
Hello everyone!

Thanks for reporting this. As @James55p mentioned above, the issue should be fixed. Please open a ticket to our support team at support@appsflyer.com if you experience any further problems with the extension.

Thank you!
