### ISSUE TITLE
Android app doesn't track anything

### ISSUE THREAD

**Issue by kalashot** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#24]
Hi,

I have a game in Play Google with AppsFlyer ANE integrated. But it doesn't track anything. Dashboard is empty. 

I added a test device and built a very simple app for integration test. But when I install it (directly from FlashDevelop) and run it I see only "Clicks" increment in my dashboard. There are neither organic installs nor non organic  installs. 

Here are my Main.as, application.xml and logcat.txt files:

**Main.as (test app):**
package
{
	import flash.display.Sprite;
	import AppsFlyerInterface;
	import AppsFlyerEvent;
	
	[SWF(frameRate = "60", backgroundColor = "#000000")]
	public class Main extends Sprite
	{
		private static var appsFlyer:AppsFlyerInterface;
		
		public function Main()
		{
			appsFlyer = new AppsFlyerInterface();
			appsFlyer.init("myDevKey", null);
			appsFlyer.startTracking("myDevKey", null);
			appsFlyer.setDebug(true);
			appsFlyer.trackAppLaunch();
		}
	}
}

**application.xml android manifest:** 
`
<manifest android:installLocation="auto">
	<uses-sdk android:minSdkVersion="15" />
	<uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<permission android:name="com.appsflyer.sample.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
	<application android:enabled="true">
		<activity android:excludeFromRecents="false">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<receiver android:name="com.appsflyer.MultipleInstallBroadcastReceiver" android:exported="true">
			<intent-filter>
				<action android:name="com.android.vending.INSTALL_REFERRER" />
			</intent-filter>
		</receiver>
		<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
			</intent-filter>
		</receiver>
		<service android:name="com.appsflyer.InstanceIDListener" android:exported="false">
			<intent-filter>
				<action android:name="com.google.android.gms.iid.InstanceID" />
			</intent-filter>
		</service>
		<service android:name="com.appsflyer.FirebaseInstanceIdListener">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
			</intent-filter>
		</service>
	</application>
</manifest>
`

**logcat.txt**:
D/AppsFlyer_5.2.0( 3434): Initializing AppsFlyer SDK: (v5.2.0.311)
V/AppsFlyer_5.2.0( 3434): (00:00:00:059) [main] is Permission Available: com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE; res: 0
D/AppsFlyer_5.2.0( 3434): (00:00:00:060) [main] Install referrer is allowed
W/AppsFlyer_5.2.0( 3434): (00:00:00:061) [main] AFInstallReferrer instance already created
I/AppsFlyer_5.2.0( 3434): (00:00:00:062) [main] Sending first launch for this session!
I/AppsFlyer_5.2.0( 3434): (00:00:00:215) [Thread-4154] sendTrackingWithEvent from activity: android.app.Application
I/AppsFlyer_5.2.0( 3434): (00:00:00:217) [Thread-4154] Trying to fetch GAID..
E/GooglePlayServicesUtil( 3434): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
D/AppsFlyer_5.2.0( 3434): (00:00:00:259) [main] InstallReferrer connected
I/AppsFlyer_5.2.0( 3434): (00:00:00:260) [Thread-4154] WARNING: Google Play Services is missing.
I/AppsFlyer_5.2.0( 3434): (00:00:00:295) [main] sendTrackingWithEvent from activity: android.app.Application
I/AppsFlyer_5.2.0( 3434): (00:00:00:412) [Thread-4154] ******* sendTrackingWithEvent: Launch
V/AppsFlyer_5.2.0( 3434): (00:00:00:418) [Thread-4154] OS SDK is=22; use KeyStore
I/AppsFlyer_5.2.0( 3434): (00:00:00:422) [Thread-4154] Initialising KeyStore..
I/AppsFlyer_5.2.0( 3434): (00:00:00:438) [Thread-4154] Creating a new key with alias: com.appsflyer,KSAppsFlyerId=xxxxxxxx-xxxxxxxxxxxxxx,KSAppsFlyerRICounter=0
I/AppsFlyer_5.2.0( 3434): (00:00:03:192) [Thread-4154] IMEI was not collected.
E/GooglePlayServicesUtil( 3434): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
I/AppsFlyer_5.2.0( 3434): (00:00:03:197) [Thread-4154] Android ID was not collected.
D/AppsFlyer_5.2.0( 3434): (00:00:03:214) [Thread-4154] AppsFlyer: first launch detected
I/AppsFlyer_5.2.0( 3434): (00:00:03:216) [Thread-4154] AppsFlyer: first launch date: 2020-04-30_001923+0000
W/AppsFlyer_5.2.0( 3434): (00:00:03:219) [Thread-4154] Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
D/AppsFlyer_5.2.0( 3434): (00:00:03:221) [Thread-4154] didConfigureTokenRefreshService=false
D/AppsFlyer_5.2.0( 3434): (00:00:03:222) [Thread-4154] No deep link detected
I/AppsFlyer_5.2.0( 3434): (00:00:03:248) [Thread-4154] AppsFlyerLib.sendTrackingWithEvent
V/AppsFlyer_5.2.0( 3434): (00:00:03:251) [Thread-4154] is Permission Available: com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE; res: 0
D/AppsFlyer_5.2.0( 3434): (00:00:03:252) [Thread-4154] Install referrer is allowed

I noticed that "The Google Play services resources were not found" so the GAID was not fetched. This applies to single AppsFlyerAIRExtension.ane and to set of AppsFlyerAIRExtension-witout-gp-support.ane + google play services ANE'S form other developers (I tried ones from distriqt/mayflashlabs/ironsource)

Can you please review my code and tell me what is wrong?

Thank you.

**Comment by kamranpirwani** [comment]
Experiencing the same issue here, any luck? @kalashot

**Comment by kalashot** [comment]
Hi,
Yes, just use the latest ane from the bin folder. It is a deprecated v4.10. But it works )

**Comment by kamranpirwani** [comment]
@kalashot Thanks for the fast response.So you  were able to use their SDK Integration Test and see it show up on the Dashboard with v4.10?

**Comment by kalashot** [comment]
Yes

**Comment by sokoloff06** [comment]
@kamranpirwani @kalashot thanks for raising this up! We have found an issue with the latest ANE release and downgraded the master branch to v4.10. We are looking for a solution to make the ANE work with the latest SDK version and will update the repository as soon as we find it. Thank you!
