### ISSUE TITLE
Support for setSharingFilterForAllPartners from SDK 5.4.1?

### ISSUE THREAD

**Issue by smileygamer** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#25]
Hi,

We want to use the setSharingFilterForAllPartners function from SDK 5.4.1 to make our apps CCPA compliant. When will become available for AIR?

**Comment by sokoloff06** [comment]
Hi @smileygamer!

We are working on updating the ANE to SDK v5.4.1 and adding sharing filter APIs for CCPA. We expect it to be released in the following weeks.

Thank you!

**Comment by James55p** [comment]
Thanks for this, @af-vs - with the next ANE update, will you also be able to update the ANE to make use of the new AndroidX libraries?

**Comment by sokoloff06** [comment]
@James55p we don't have this planned, but we have a version that doesn't include android-support library - `AppsFlyerAIRExtension-witout-gp-support.ane`

If you have conflicts, can you try to use this one instead and see if that helps? If not, please open a new issue with some details and we will tackle it as soon as possible independently from updating the SDK version.

Thank you!
