### ISSUE TITLE
Google adwords app install conversion tracking for iOS

### ISSUE THREAD

**Issue by ankitpate1** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#3]
Current version does not track google adwords conversion app install.
How can i incorporate google adwords conversion SDK to appsflyer ANE for ios ?
https://developers.google.com/app-conversion-tracking/docs/ios/using-sdk

**Comment by sokoloff06** [comment]
Hi!
We are closing this issue due to a lack of activity. Please feel free to re-open and let us know if that is still relevant.
Thank you!
