### ISSUE TITLE
ANE must support 64bit for iOS

### ISSUE THREAD

**Issue by shaymolho** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#4]
Hi,

Adobe air sdk 16 demands that all the ANEs in the project will support arm64 bit for iOS.
Application can't be build to ios otherwise.

This is a show-stopper for us.
(All other ANEs already support it)

Please fix ASAP

**Comment by gmeroz** [comment]
According to Apple: "October 20, 2014
Starting February 1, 2015, new iOS apps uploaded to the App Store must include 64-bit support and be built with the iOS 8 SDK, included in Xcode 6 or later. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code."

If you plan to release an update with 32bit I suggest you take the previous version. Use the history of the file. https://github.com/AppsFlyerSDK/AdobeAirExtension-AppsFlyer/commits/master/ANE/appsflyer.ane
