### ISSUE TITLE
Google uploaded warning

### ISSUE THREAD

**Issue by a9848840** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#40]
I use 
AppsFlyerAIRExtension.swc
AppsFlyerAIRExtension-witout-gp-support.ane--->ver:6.3.20

When I uploaded my apk to google play console and it gives me these warnings:

1) There is no deofuscation file associated with this APK. If you are using obfuscated code (R8 / ProGuard), you can upload a deofuscation file to make it easier to analyze and debug ANR bugs and errors. Using R8 / ProGuard can help reduce the size of the application

2) This APK contains native code, but you have not uploaded debugging symbols. We recommend that you upload a symbol file to facilitate the analysis and debugging of ANR errors and failures.

//==================

I try use aab add com.appsflyer.adobeair.ane
also get warning (1).(2)

I use aab  upload  32 bit no com.appsflyer.adobeair.ane
(1).(2) warning disappeared

AirSDK:33.1.1.554
jdk1.8.0_144

Is there a way to resolve the warning?

**Comment by sokoloff06** [comment]
Hi @a9848840 

We do not provide deobfuscation files for our SDK as this is a security measure. You can safely ignore the warning and in case you get some cryptic-looking ANR or crash stack traces pointing to our SDK, you can always reach out and we will help you to sort it out.

Thanks!
