### ISSUE TITLE
Uninstall measurement

### ISSUE THREAD

**Issue by shaymolho** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#41]
# Report
We would like to implement AppsFlyer uninstall measurement, both in android and iOS.
We are using an ANE for firebase FCM - https://github.com/distriqt/ANE-Firebase
In android I followed the steps outlined in [appsflyer tutorial](https://support.appsflyer.com/hc/en-us/articles/360017822118) but i didn't know how to proceed with https://support.appsflyer.com/hc/en-us/articles/360017822118#integrate-fcm-into-the-app

## Plugin Version
v6.2.31

## On what Platform are you having the issue?
ios and android

**Comment by shaymolho** [comment]
@af-vs any update on this?

**Comment by sokoloff06** [comment]
Hi @shaymolho!

Can you please clarify which step are you struggling with? 

In the essence, to make it work in Android, you need to forward device push notification token to AppsFlyer SDK either automatically registering our FirebaseMessagingServiceListener in AndroidManifest OR by passing device token (that you should be able to get from Firebase FCM ANE) via the ActionScript API `registerUninstall(deviceToken:String):void` of the `AppsFlyerInterface`

As for the iOS, you can pass the device token (that you would normally get from [application(_:didRegisterForRemoteNotificationsWithDeviceToken:)
](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application) in native code) to the same ActionScript API as for Android. I'm not sure if and how it is possible to get this token using ANE for Firebase FCM on iOS.
