### ISSUE TITLE
Missing Android Intel Support

### ISSUE THREAD

**Issue by MasterVivi** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#6]
Would it be possible if the ANE could be recompiled with Android-x86 support for intel devices? It's an area we really need to support.

**Comment by gmeroz** [comment]
Hi,
We have a new build but no device to test it on. Please contact support@appsflyer.com by email so we can provide you the ANE to check if it solves the problem.

Best,
Gil

**Comment by dregerATiTD** [comment]
been over a year, any joy?  I see this is still open.

**Comment by sokoloff06** [comment]
Hi!

Today ANE supports Android-ARM, Android-ARM64, and Android-x86. If you encounter any problems, please open a new issue with the relevant details.

Thank you!
