### ISSUE TITLE
Latest AppsFlyer SDK for Adobe Air crashing the application

### ISSUE THREAD

**Issue by shaymolho** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#7]
Hi,

we tried to upgrade our app's AppsFlyer SDK for Adobe-Air to the latest version in order to get the support for applie 64-bit extension requirement.
After replacing the ANE to AppsFlyer latest and building the application, the application crashes immediately when launched.
Setting the ANE to the previous version (has no 64 bit support) solves the problem.

We need to solve this issue asap. 
At June 1 it won't be apple to upload Application to the appstore that do not compiled in 64 bit.

Thanks,
Shay

Here is log snippet from Android's logcat:

I/ActivityManager(  537): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=air.com.wizits.slotagramLocalDev/.AppEntry (has extras)} from uid
 10036 on display 0
I/ActivityManager(  537): Start proc air.com.wizits.slotagramLocalDev for activity air.com.wizits.slotagramLocalDev/.AppEntry: pid=29832 uid=10438 gids={50438, 9997, 3003, 1028, 1015} abi=ar
meabi-v7a
I/WindowManager(  537): Screenshot max retries 4 of Token{2ff00edd ActivityRecord{378762b4 u0 air.com.wizits.slotagramLocalDev/.AppEntry t484 f}} appWin=Window{37b7694d u0 SurfaceView} drawS
tate=1
W/InputDispatcher(  537): channel '1f6fac77 air.com.wizits.slotagramLocalDev/air.com.wizits.slotagramLocalDev.AppEntry (server)' ~ Consumer closed input channel or an error occurred.  events
=0x9
E/InputDispatcher(  537): channel '1f6fac77 air.com.wizits.slotagramLocalDev/air.com.wizits.slotagramLocalDev.AppEntry (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState(  537): WIN DEATH: Window{1f6fac77 u0 air.com.wizits.slotagramLocalDev/air.com.wizits.slotagramLocalDev.AppEntry}
W/InputDispatcher(  537): Attempted to unregister already unregistered input channel '1f6fac77 air.com.wizits.slotagramLocalDev/air.com.wizits.slotagramLocalDev.AppEntry (server)'
I/ActivityManager(  537): Process air.com.wizits.slotagramLocalDev (pid 29832) has died

**Comment by gmeroz** [comment]
Hi Shay,
Can  you please provide a more detailed log (more lines) and also some more information about your device version?

Best,
Gil

**Comment by shaymolho** [comment]
Hi,
These are the only lines related to the Application.

We're using the previous version of the SDK with our app for a while on Android and iOS platforms and everything works as fine.
We tried to upgrade to the latest version because of Apple's requirement that apps will be 64bit compatible and only the new version of the SDK is compatible.

We did the following steps:
1. Upgrade the AirSdk to the latest version (version 17.0.0.124). After that the app cannot be built for ios unless you upgrade the AppsFlyer extension (but can be built for Android).
2. We build the application for Android with the Air 17 and the old AppsFlyer version - Everything works fine and the application works as always on all the devices.
3. We changed the extension to the new version, the application build finishes correctly, but when we installed the APK on the same android device the application crashes immediately when launched. The log lines i've added are the only relevant log lines from Android log.
We tried to run this APK on several android devices (among Nexus 7, Galaxy S3, Galaxy S2) and in all of them the application crashes immediately.

If it helps i can send you the working and the non working versions of the APK

and a reminder again - from June 1st we will not be able to upload our application to the appstore because of that. this is why this issue is so urgent.

Thanks,
Shay

**Comment by shanmichu** [comment]
We're facing the same problem.
Galaxy Note 2 running android 4.1.2 if that helps

**Comment by shaymolho** [comment]
Hi, any updates on this issue?

**Comment by gmeroz** [comment]
Can you please send us the APK? You can send it to support@appsflyer.com

**Comment by shaymolho** [comment]
Hi, Sent the APK to support@appsflyer.com

**Comment by dregerATiTD** [comment]
and.....?  Any Joy?

**Comment by sokoloff06** [comment]
Hi!

We are closing this issue as this is no longer relevant. Please feel free to re-open and let us know if you encounter anything similar.

Thank you!
