### ISSUE TITLE
getConversionData on iOS never finishes

### ISSUE THREAD

**Issue by nodrock** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#9]
With update to new ANE there must be a error in handling conversion data. 

``` actionscript
_afInterface.addEventListener(AppsFlyerEvent.INSTALL_CONVERSATION_DATA_LOADED, onConversationLoaded);
_afInterface.addEventListener(AppsFlyerEvent.INSTALL_CONVERSATION_FAILED, onConversationFailed);
_afInterface.getConversionData();
```

After call to getConversionData I will never get DATA_LODED or FAILED.

**Comment by soccerob** [comment]
I've also never been able to get this response back. The documentation says to listen for AppsFlyerEvent.SUCCESS which does not exist. The above code does function properly for me on android devices, but not on iOS.
@nodrock have you gotten any updates or had any success in getting this callback?

**Comment by nodrock** [comment]
Yes they updated ANE to new version and everything works as expected. You should listen to those two events in my example.

**Comment by soccerob** [comment]
Awesome! Thanks, updated the sdk and it's working for iOS now.
